package org.example.scheduler.entity;

public enum JobType {
    EVENT_REMIND_1H,
    EVENT_STARTED,
    EVENT_OPEN_REPUTATION,
    EVENT_KEEP_CHAT_POLL,
    EVENT_RESOLVE_KEEP_CHAT,
    EVENT_CLOSE_REPUTATION,
    EVENT_DELETE_CHAT_AFTER_CANCEL,
    EVENT_DELETE_CHAT_AFTER_KEEP_FAIL,
    REFRESH_TOKEN_CLEANUP
}
