server:
  port: 8085

spring:
  application:
    name: like
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/social_like_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  logging:
    level:
      org.springframework.cloud.gateway: DEBUG
      reactor.netty.http.client: DEBUG
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG
      org.springframework.orm.jpa: DEBUG